### ISSUE TITLE
导入规则后不生效的解决办法

### ISSUE THREAD

**Issue by yi0322** [scp-079/foxygfw#1]
开启“同步设置”时导入规则后不生效，依然是全局代理模式，再次打开“模式”会发现导入的规则没有被保存

解决办法：
关闭“同步设置”后导入保存即可

**Comment by xiao-x-s** [comment]
感谢提及，事实上我也遇到了这个问题，也是通过关闭「同步」后解决的。
这个是 FoxyProxy 的已知问题，参见： https://github.com/foxyproxy/firefox-extension/issues/95
FoxyProxy 的作者目前也没有什么比较好的解决办法。
稍后将在 README 中提及到此问题并附加 “关闭「同步」” 的办法。
